import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
customers = pd.read_csv("Customers.csv")
products = pd.read_csv("Products.csv")
transactions = pd.read_csv("Transactions.csv")
print(customers.info())
print(customers.isnull().sum())
print(customers.duplicated().sum())
print(products.info())
print(products.isnull().sum())
print(products.duplicated().sum())
print(transactions.info())
print(transactions.isnull().sum())
print(transactions.duplicated().sum())
plt.figure(figsize=(8, 5))
sns.countplot(data=customers, x='Region')
plt.title('Customer Distribution by Region')
plt.show()
transactions['TransactionDate'] = pd.to_datetime(transactions['TransactionDate'])
transactions['Month'] = transactions['TransactionDate'].dt.to_period('M')
monthly_sales = transactions.groupby('Month').size()
plt.figure(figsize=(10, 5))
monthly_sales.plot(kind='bar', color='teal')
plt.title('Monthly Transactions')
plt.ylabel('Number of Transactions')
plt.show()
top_products = transactions.groupby('ProductID')['Quantity'].sum().sort_values(ascending=False).head()
print(top_products)
transactions['TotalSpend'] = transactions['Quantity'] * transactions['Price']  # Or use 'TotalValue' if available
customer_spending = transactions.groupby('CustomerID')['TotalSpend'].sum()
top_customers = customer_spending.sort_values(ascending=False).head()
print(top_customers)
product_quantity = transactions.groupby('ProductID')['Quantity'].sum().sort_values(ascending=False).head()
print(product_quantity)
with open("Sonal_Garg_EDA.pdf", "w") as f:
    f.write("Business Insights:\n")
    f.write("1. Region distribution shows a mix of North, South, East, and West.\n")
    f.write("2. Monthly transactions show an increasing trend.\n")
    f.write("3. Top 5 products by quantity sold are identified.\n")
    f.write("4. Top customers based on total spending can be targeted for retention.\n")
    f.write("5. Product quantity patterns help identify high-demand items.\n")
